In [ ]:
import torch
a = torch.rand(2,2)
b = torch.rand(2,2)
c = a + b
d = torch.add(a,b)
#和自身相加
a.add_(5)
d

In [ ]:
b

In [ ]:
c

In [ ]:
d

In [ ]:
a

# 不同张量之间的乘法

In [ ]:
a*b

In [ ]:
a.mul(b)

In [ ]:
#和自身相乘
a.mul_(b)

In [ ]:
a

In [ ]:
b

In [3]:
import torch
a1 = torch.rand(10000,10000)
b1 = torch.rand(10000,10000)
# %timeit a1.matmul(b1)

13.3 s ± 1.7 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]:
#将张量转移到GPU
a1_g = a1.cuda()
b1_g = b1.cuda()

%timeit a1_g.matmul(b1_g)

373 ms ± 9.86 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)


373 ms ± 9.86 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)